stages:
  - buildandtest
  - deploy

buildandtest:
  stage: buildandtest
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker run -v ${PWD}:/work fpco/stack-build bash -c 'cd /work && stack setup && stack install && /root/.local/bin/blog build'
    - docker build -t registry.gitlab.com/henripal/backend ./backend/.
    - docker build -t registry.gitlab.com/henripal/frontend ./frontend/.
    - docker push registry.gitlab.com/henripal/backend
    - docker push registry.gitlab.com/henripal/frontend

deploy:
  stage: deploy
  script:
    - ssh root@159.203.183.2 touch hiya.txt