stages:
  - buildandtest
  - deploy

buildandtest:
  stage: buildandtest
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/henripal/webapp_template/backend ./backend/.
    - docker push registry.gitlab.com/henripal/webapp_template/backend
    - docker build -t registry.gitlab.com/henripal/webapp_template/frontend ./frontend/.
    - docker push registry.gitlab.com/henripal/webapp_template/frontend

deploy:
  stage: deploy
  script:
    - scp docker-compose.yml root@159.203.183.2:~/
    - ssh root@159.203.183.2 docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - ssh root@159.203.183.2 docker-compose up -d

