stages:
  - build_and_unit_test
  - e2e_test
  - deploy

build_and_unit_test:
  stage: build_and_unit_test
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/henripal/webapp_template/backend ./backend/.
    - docker push registry.gitlab.com/henripal/webapp_template/backend
    - docker build -t registry.gitlab.com/henripal/webapp_template/frontend ./frontend/.
    - docker push registry.gitlab.com/henripal/webapp_template/frontend

e2e_test:
  stage: e2e_test
  script:
    - docker kill $(docker ps -q)
    - docker run -d -p 8888:8888 registry.gitlab.com/henripal/webapp_template/backend
    - docker build -t frontend_test -f ./frontend/Dockerfile.e2e ./frontend/.
    - docker run -p 8080:8080 frontend_test

deploy:
  stage: deploy
  script:
    - scp docker-compose.yml root@159.203.183.2:~/
    - ssh root@159.203.183.2 docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - ssh root@159.203.183.2 docker-compose down --rmi all --remove-orphans
    - ssh root@159.203.183.2 docker-compose up -d

