stages:
  - build_and_unit_test
  - deploy

build_and_unit_test:
  stage: build_and_unit_test
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build --build-arg DBIP='159.89.230.190' -t registry.gitlab.com/henripal/webapp_template/backend ./backend/.
    - docker push registry.gitlab.com/henripal/webapp_template/backend
    - docker build --build-arg DBIP='159.89.230.190' -t registry.gitlab.com/henripal/webapp_template/frontend ./frontend/.
    - docker push registry.gitlab.com/henripal/webapp_template/frontend


deploy:
  stage: deploy
  script:
    - scp docker-compose.yml root@159.203.183.2:~/
    - ssh root@159.203.183.2 docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - ssh root@159.203.183.2 docker-compose down --rmi all --remove-orphans
    - ssh root@159.203.183.2 docker-compose up -d -e DBIP='159.89.230.190' 

