stages:
  - buildandtest
  - deploy

buildandtest:
  stage: buildandtest
  script:
    - docker build -t backend ./backend/.
    - docker build -t frontend ./frontend/.

deploy:
  stage: deploy
  script:
    - ssh root@159.203.183.2 touch hiya.txt