version: '3'

services:
    frontend:
        build: ./frontend/


    caddy:
        image: abiosoft/caddy
        ports:
            - 8080:8080
        volumes: 
            - ./frontend/dist:/srv
            - ./frontend/Caddyfile:/etc/Caddyfile
        depends_on:
            - frontend

    backend:
        build: ./backend/
        ports:
            - 8888:8888