version: '3'

services:
    frontend:
        environment:
          - VUE_APP_DATA_URL="http://159.203.183.2:8888/data"
        image: registry.gitlab.com/henripal/webapp_template/frontend 
        ports:
          - 8080:8080

    backend:
        image: registry.gitlab.com/henripal/webapp_template/backend 
        ports:
            - 8888:8888