version: '3'

services:
    frontend:
        image: registry.gitlab.com/henripal/webapp_template/frontend 


    caddy:
        image: abiosoft/caddy
        ports:
            - 8080:8080
        volumes: 
            - ./frontend/dist:/srv
            - ./frontend/Caddyfile:/etc/Caddyfile
        depends_on:
            - frontend

    backend:
        image: registry.gitlab.com/henripal/webapp_template/backend 
        ports:
            - 8888:8888