version: '3'

services:
    frontend:
        build: ./frontend/
        ports:
          - 80:80

    backend:
        build: ./backend/
        ports:
            - 8888:8888

    model_backend:
        build: ./model_backend/
        ports:
            - 8008:8008