version: '3'

services:
    frontend:
        image: registry.gitlab.com/henripal/webapp_template/frontend 
        ports:
          - 8080:8080

    backend:
        image: registry.gitlab.com/henripal/webapp_template/backend 
        ports:
            - 8888:8888